# Generated by Django 4.2.23 on 2025-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_name_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Jeans', 'Jeans'), ('Dresses', 'Dresses'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Long-Dresses', 'Long-Dresses')], default='T-Shirts', max_length=50),
            preserve_default=False,
        ),
    ]
